version: "3.1"
services:
  db-lumen:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - lumen
    volumes:
      - db_lumen:/var/www/html/
networks:
  lumen:
    driver: bridge
volumes:
  db_lumen:
    driver: local
